// <auto-generated />
using System;
using BandWebApi.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BandWebApi.Migrations
{
    [DbContext(typeof(BandAlbumContext))]
    [Migration("20201017003715_intial")]
    partial class intial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BandWebApi.Entity.Album", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(400)")
                        .HasMaxLength(400);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.HasIndex("BandId");

                    b.ToTable("Albums");

                    b.HasData(
                        new
                        {
                            Id = new Guid("664e3727-fe08-4bba-84a0-918b522443b3"),
                            BandId = new Guid("a791d1e5-9ec5-427c-b1da-5152fe3b2798"),
                            Description = "One of the best heavy metal album ever",
                            Title = "Master Of Poppets"
                        },
                        new
                        {
                            Id = new Guid("381aa698-3a67-4322-8c4f-e8fa472fdf9d"),
                            BandId = new Guid("4035ab45-7b8e-41ff-a181-d8f81b6ca633"),
                            Description = "Amazing Rock album with raw sound",
                            Title = "Appetite for Destruction"
                        },
                        new
                        {
                            Id = new Guid("f4393aad-4c77-4a05-8b47-8f84d8841822"),
                            BandId = new Guid("515f0e4b-ec42-476d-b408-e28579352088"),
                            Description = "Very groovy album",
                            Title = "Waterloo"
                        },
                        new
                        {
                            Id = new Guid("5945a30d-0c8e-4c19-b51f-6375f0b56b46"),
                            BandId = new Guid("f51e023d-97de-44ec-bbfb-ff24ef39bdf0"),
                            Description = "Arguably one of the best albums bu Oasis",
                            Title = "Be Here Now"
                        },
                        new
                        {
                            Id = new Guid("1754795b-b366-4e24-abc9-ab10bb60455d"),
                            BandId = new Guid("68ffce07-ae53-43cb-a8a8-260f95ca4743"),
                            Description = "Awesome Debut album by A-ha",
                            Title = "Huning High and Low "
                        });
                });

            modelBuilder.Entity("BandWebApi.Entity.Band", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Founded")
                        .HasColumnType("datetime2");

                    b.Property<string>("MainGenre")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Bands");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a791d1e5-9ec5-427c-b1da-5152fe3b2798"),
                            Founded = new DateTime(1980, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MainGenre = "Heavy Metal",
                            Name = "Metallica"
                        },
                        new
                        {
                            Id = new Guid("4035ab45-7b8e-41ff-a181-d8f81b6ca633"),
                            Founded = new DateTime(1985, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MainGenre = "Rock",
                            Name = "Gnus N Roses"
                        },
                        new
                        {
                            Id = new Guid("515f0e4b-ec42-476d-b408-e28579352088"),
                            Founded = new DateTime(1965, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MainGenre = "Disco",
                            Name = "ABBA"
                        },
                        new
                        {
                            Id = new Guid("f51e023d-97de-44ec-bbfb-ff24ef39bdf0"),
                            Founded = new DateTime(1991, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MainGenre = "Alternative",
                            Name = "Oasis"
                        },
                        new
                        {
                            Id = new Guid("68ffce07-ae53-43cb-a8a8-260f95ca4743"),
                            Founded = new DateTime(1981, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MainGenre = "Pop",
                            Name = "A-ha"
                        });
                });

            modelBuilder.Entity("BandWebApi.Entity.Album", b =>
                {
                    b.HasOne("BandWebApi.Entity.Band", "Band")
                        .WithMany("Albums")
                        .HasForeignKey("BandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
